### PR TITLE
Make fairing asynchronous

### PR DESCRIPTION
**Pull request by sd2k**
Make the fairing compatible with the asynchronous version of Rocket. This won't be merged until async Rocket is released.

### CODE REVIEW

**Comment by svenstaro** [comment]
Could you rebase this and update it for current Rocket master? I'd like to give it a test drive. :)

**Comment by sd2k** [comment]
@svenstaro This should already support the latest Rocket master as of 64f3ff7 - I made the changes a couple of days ago! Are you having issues getting it to compile?

**Comment by svenstaro** [comment]
Oh, nevermind then. I just thought it was weird that you conflict with your target branch currently. I'll just use your branch directly for the time being but I think it'd be great if you could fix the conflicts, too. :)

**Comment by sd2k** [comment]
@svenstaro I've merged `master` into this branch now so the conflicts should be sorted :+1:

**Comment by svenstaro** [comment]
Super noice! Will check it out.

**Pull request merged**
